export const SECTION_COMPLETE_REQUEST = 'SECTION_COMPLETE_REQUEST'
export const SECTION_COMPLETE_SUCCESS = 'SECTION_COMPLETE_SUCCESS'
export const SECTION_COMPLETE_FAIL = 'SECTION_COMPLETE_FAIL'
export const SECTION_RESET_STATUS = 'SECTION_RESET_STATUS'